### ISSUE TITLE
Add replace method to LicenseExpression

### ISSUE THREAD

**Issue by pombredanne** [nexB/license-expression#10]
I would like to replace a expression and by another expression in a given expression.
The semantics should be the same as the `string.replace` [stdlib](https://docs.python.org/2.7/library/string.html?highlight=string%20replace#string.replace) function eg:
```
string.replace(s, old, new[, maxreplace])

    Return a copy of string s with all occurrences of substring old replaced by new. 
    If the optional argument maxreplace is given, the first maxreplace occurrences are replaced.
```
e.g. the function should apply to all exact sub expressions matching old in the expression tree and should not be recursive like in `string.replace`:
```
>>> 'foobarbar'.replace('foobar', 'foo')
'foobar'
```

The maxreplace is not needed.

**Comment by pombredanne** [comment]
See also this https://github.com/bastikr/boolean.py/issues/66

**Comment by pombredanne** [comment]
The subs method in https://github.com/bastikr/boolean.py/issues/66 is all we need and this is already there.
I am adding some tests to verify that this works as expected.

**Comment by yash-nisar** [comment]
@pombredanne I think this has been fixed, so can we close this ? Please correct me if I am wrong. :)

**Comment by yash-nisar** [comment]
Ping @pombredanne

**Comment by pombredanne** [comment]
@yash-nisar good catch. Thanks! closing.
