### ISSUE TITLE
Typo in boolean.py.ABOUT download_url

### ISSUE THREAD

**Issue by tdruez** [nexB/license-expression#12]
https://github.com/nexB/license-expression/blob/master/thirdparty/prod/boolean.py.ABOUT#L3

Yet another reason for an integration tool as described in https://github.com/nexB/attributecode/issues/281

**Comment by srbcheema1** [comment]
@pombredanne This issue has been fixed in https://github.com/nexB/license-expression/commit/b2170f83bb06d44c5238d43eb576aa4e02b83a9a so it must be closed now.
Correct me if I got something wrong.

**Comment by yash-nisar** [comment]
Yes @srbcheema1 you're right, this should be closed @pombredanne :)
