### ISSUE TITLE
Add Python 3.6 to Travis and Appveyor tests 

### ISSUE THREAD

**Issue by pombredanne** [nexB/license-expression#22]

**Comment by pombredanne** [comment]
See also this failing build https://github.com/nexB/license-expression/pull/23#partial-pull-merging for Python 3.5 ....

**Comment by p8107406332** [comment]
This is my issue and I am new here can anybody help me to solve it

**Comment by p8107406332** [comment]
#first issue

**Comment by pombredanne** [comment]
Thank you for your enthusiasm: you have to make your own  research for this and understand what the problem is. Hint: check the travis and appevyor configuration files in this repo and read the documentation for these CI services.

**Comment by p8107406332** [comment]
thanks for giving hint

**Comment by pombredanne** [comment]
@p8107406332 I am pushing something as I need this ASSAP before a new release

**Comment by pombredanne** [comment]
Fixed and merged in master
