### ISSUE TITLE
Advertise installation via AUR

### ISSUE THREAD

**Issue by mxmehl** [nexB/license-expression#40]
On Arch Linux and its derivates, users can also install license-expression using [this AUR](https://aur.archlinux.org/packages/python-license-expression/). It would be nice if this was reflected in the README and other docu :)

I had to package it there because its a dependency for [reuse](https://aur.archlinux.org/packages/reuse/).

If you have any feedback about the AUR package, please let me know!

**Comment by pombredanne** [comment]
@mxmehl that's awesome! do you mind for a PR?

**Comment by pombredanne** [comment]
@mxmehl FWIW, I am also a maintainer on boolean.py

**Comment by mxmehl** [comment]
> @mxmehl that's awesome! do you mind for a PR?

Thanks! Unfortunately not within the next 3 week as I will be on vacation from tomorrow on :(

> @mxmehl FWIW, I am also a maintainer on boolean.py

Do you refer to the "Maintainers" line in the PKGBUILD line? I thought this was meant to be the maintainer of this file, not the whole package.

**Comment by pombredanne** [comment]
@mxmehl re

> Thanks! Unfortunately not within the next 3 week as I will be on vacation from tomorrow on :(

That's does not sound like something "Unfortunate" to me ;)



>>    @mxmehl FWIW, I am also a maintainer on boolean.py

>Do you refer to the "Maintainers" line in the PKGBUILD line? I thought this was meant to be the maintainer of this file, not the whole package.


I was just alluding to the fact that I am also committing there and that `license-expression` relies heavily on `boolean.py` as a FYI.
