### ISSUE TITLE
Improve readability of WITH expressions

### ISSUE THREAD

**Issue by pombredanne** [nexB/license-expression#45]
Expressions such as "Foo WITH Bar OR Baz" are not super readable because the operator precedence is not something super intuitive.
It would be great to have the option to render an expression this way: "(Foo WITH Bar) OR Baz"

**Comment by pombredanne** [comment]
This has been merged but keeping it open until we have a changelog

**Comment by majurg** [comment]
#48 has been merged, and `license-expression` now has a changelog. Closing this.
