### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by mxmehl** [nexB/license-expression#47]
Would it be possible to introduce a changelog file or a verbose description for the Git tags/releases that lists new features and especially breaking changes? Ideally, it would follow the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) spec.

I am maintainer of this project's [AUR (Arch Linux) package](https://aur.archlinux.org/packages/python-license-expression/) and of the [REUSE tool's package](https://aur.archlinux.org/packages/reuse/) which depends on license-expression. It's hard for me to tell whether a new version of license-expression changes a function that tools depending on it rely on.

**Comment by pombredanne** [comment]
@mxmehl you are so right!
Let's start this and ensure this is also a check we do before any release!

**Comment by pombredanne** [comment]
@mxmehl thanks again for the report. And @majurg thanks you for fixing this :bowing_man:

**Comment by mxmehl** [comment]
Thank you for the fast fix. As a result, I felt confident to update the AUR package :)

**Comment by pombredanne** [comment]
@mxmehl thank you for bringing this up and double thank you for maintaining this package in AUR!
