### ISSUE TITLE
mit AND (mit OR bsd-new) incorrectly simplifies to mit

### ISSUE THREAD

**Issue by majurg** [nexB/license-expression#49]
```
>>> from license_expression import Licensing
>>> Licensing().parse('mit AND (mit OR bsd-new)').simplify()
LicenseSymbol('mit', is_exception=False)
```

From the above output, one can see that `mit AND (mit OR bsd-new)` simplifies down to just `mit`. If this were just boolean logical elements, this result would be correct. However, when its a license-expression, we are loosing data (this case, the `bsd-new` key). 

In a perfect world, I would like the result to be simply reduce to `mit OR bsd-new`.

**Comment by pombredanne** [comment]
Actually I think that `mit AND (mit OR bsd-new)` should be reduced to `mit AND (mit OR bsd-new)` and nothing else. (e.g. not be reduced).
IMHO the approach should be to have an option to keep the choices and treat these as something that cannot be simplified  further (such that the choice stays)

So  `mit AND (mit OR bsd-new) AND mit AND (mit OR bsd-new)`  should be reduced to `mit AND (mit OR bsd-new)` but not your exmaple above IMHO.

**Comment by pombredanne** [comment]
My point is that in `mit AND (mit OR bsd-new)` the mit terms would always apply and the bsd-new terms may apply depending on your choice, so the terms cannot be reduce to `mit OR bsd-new` only.

**Comment by DennisClark** [comment]
Agreed with @pombredanne
