### ISSUE TITLE
Add function to combine expressions

### ISSUE THREAD

**Issue by pombredanne** [nexB/license-expression#51]
See https://github.com/nexB/scancode-toolkit/blob/483e47a69e24a0b9ac08f0861ce63dbb7be457f9/src/packagedcode/utils.py#L153

**Comment by joy2306** [comment]
hey @pombredanne  i want to contribute to this issue , can u help me out a little bit , i am a complete beginer and want to start my opensource journey . can u let me know is there any specific fameworks that i should learn to contribute here .
    Thanks in advance.

**Comment by pombredanne** [comment]
@joy2306 Thanks for your enthusiasm!
This is likely not really a beginner ticket, though you are welcomed to get a stab at it.
The gist is to move this  https://github.com/nexB/scancode-toolkit/blob/483e47a69e24a0b9ac08f0861ce63dbb7be457f9/src/packagedcode/utils.py#L153 to this project and add thorough tests.

You would need to study the whole code here in details to understand how this library (and its backing boolean.py library) works.

**Comment by pombredanne** [comment]
This has been added at https://github.com/nexB/license-expression/blob/88977ce42111813109519b6987bab491979f5562/src/license_expression/__init__.py#L1417
with https://github.com/nexB/license-expression/commit/5af569ff64edefb707545c73c8f2fb9e45789217 by @chinyeungli 
Closing now!
