### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by chinyeungli** [nexB/license-expression#61]
https://github.com/nexB/license-expression#development

I think this is not sync with the current `configure` script as we are now using `configure --dev`  to have the testing utilities installed and the binaries lie under `tmp/bin/` instead of `bin` (the binaries location seem different between `configure` and `configure.bat`)

**Comment by pombredanne** [comment]
@chinyeungli do you mind for a PR?

**Comment by chinyeungli** [comment]
@pombredanne the windows' configure will put all the libs under `/tmp/Scripts/` while the linux configure put all the libs under `/tmp/bin/` 
Is there any way to sync this? or perhaps create a symbolic link at `/tmp/bin/` pointing to `/tmp/Scripts/`? but I don't know how to do that with the current `setup.cfg` or `configure.bat`
feedback/comment/instruction are welcome

**Comment by pombredanne** [comment]
> Is there any way to sync this? or perhaps create a symbolic link at /tmp/bin/ pointing to /tmp/Scripts/? but I don't know how to do that with the current setup.cfg or configure.bat

There is a way called junctions and it used to be set with this in scancode in the past https://github.com/nexB/scancode-toolkit/commit/6290f39fada2e7511ff2fdb1c757ecebe49b9393
It was removed as this was causing more problems than using the Scripts path.... which we do not control and is what "virtualenv" does by default (and cannot be changed)

**Comment by pombredanne** [comment]
See also https://github.com/pypa/virtualenv/issues/296

**Comment by chinyeungli** [comment]
I've figuered out to create a junction by adding the following line of code in the `configure.bat`
```
mklink /J %CFG_ROOT_DIR%\%VIRTUALENV_DIR%\bin %CFG_ROOT_DIR%\%VIRTUALENV_DIR%\Scripts
```
such as at https://github.com/nexB/license-expression/blob/master/configure.bat#L144

Will that work?
(It seems to work on my other repo)

**Comment by AyanSinhaMahapatra** [comment]
README has been updated, closing this.
