### ISSUE TITLE
Please provide a proper documentation

### ISSUE THREAD

**Issue by stephanlachnit** [nexB/license-expression#73]
Currently the docs folder only contains a placeholder documentation. It would be nice if license-expression would at least have an automatically created API documentation via [`sphinx.ext.autodoc`](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html).

**Comment by pombredanne** [comment]
@stephanlachnit Yes! you are right!

**Comment by pombredanne** [comment]
BTW I see you may be using it in https://github.com/stephanlachnit/dep5convert which looks very nice!  :heart: 
You may fancy checking out this https://github.com/nexB/debian-inspector to deal with the basics of deb822 and copyright files and this for extensive Debian copyright support https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/debian_copyright.py  .... and this also includes some license-expression usage examples

**Comment by pombredanne** [comment]
@stephanlachnit could I interest you in a PR for the doc? :angel: :innocent: 
@AyanSinhaMahapatra do you know if this repo is this enabled for autodoc publishing in RTD otherwise?

**Comment by stephanlachnit** [comment]
> You may fancy checking out this https://github.com/nexB/debian-inspector to deal with the basics of deb822 and copyright files and this for extensive Debian copyright support https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/debian_copyright.py .... and this also includes some license-expression usage examples

Cool, I will check it out!

> could I interest you in a PR for the doc?

See #74.
